### ISSUE TITLE
Security Scheme hard coded to basic

### ISSUE THREAD

**Issue by vishalpatel-te** [essencebit/SignalRSwaggerGen#27]
Is it possible to define the security scheme for the swagger? Instead of hard coding to basic, perhaps a parameter on SignalRHubAttribute to specify?
https://github.com/Dorin-Mocan/SignalRSwaggerGen/blob/f400c31d6bd130618cdb650192bdf6caa87acfce/SignalRSwaggerGen/SignalRSwaggerGen/SignalRSwaggerGen.cs#L134

							
In .Net6, if we are using Bearer token for authentication, the Hub shows no documentation under authorize attribute.

**Comment by Dorin-Mocan** [comment]
@vishalpatel-te , I'll check and come back to you asap. Thanks!

**Comment by Dorin-Mocan** [comment]
@vishalpatel-te , hello! Could you please elaborate more on this statement? 
"In .Net6, if we are using Bearer token for authentication, the Hub shows no documentation under authorize attribute."
What do you mean by "under authorize attribute"?
As for specifying security scheme, I'm working on it and soon will make a release.

**Comment by vishalpatel-te** [comment]
@Dorin-Mocan I meant something like following:
![image](https://user-images.githubusercontent.com/99941109/192025932-699fcda9-e964-4008-ad2a-81a971e6e560.png)

**Comment by Dorin-Mocan** [comment]
@vishalpatel-te , I am sorry, but I do not get what you mean. Please share more details(some code maybe, bigger screenshots, etc.). Thank you!

**Comment by Dorin-Mocan** [comment]
@vishalpatel-te , I released some time ago a new version that allows specifying a security scheme.
